{% set name = "dos2unix" %}
{% set version = "7.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://waterlan.home.xs4all.nl/{{name}}/{{name}}-{{ version }}.tar.gz
    sha256: 264742446608442eb48f96c20af6da303cb3a92b364e72cb7e24f88239c4bf3a

build:
  skip: true   # [win]
  number: 2
  script:
    - sed -i.1.bak s+CFLAGS_USER\ \ \ \ =+CFLAGS_USER\ \ \ \ ="\-L\$\{CONDA_PREFIX\}/lib \-I\$\{CONDA_PREFIX\}/include"+g Makefile
    - sed -i.2.bak s+LDFLAGS_USER\ \ \ \ =+LDFLAGS_USER\ \ \ \ ="\-L\$\{CONDA_PREFIX\}/lib \-I\$\{CONDA_PREFIX\}/include"+g Makefile
    - make prefix=$CONDA_PREFIX all
    - make prefix=$CONDA_PREFIX install

requirements:
  build:
    - {{ compiler ('c') }}
    - make
    - gettext
test:
  commands:
    - dos2unix -h
    - unix2dos -h

about:
  home: https://waterlan.home.xs4all.nl/dos2unix.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: "Convert text files with DOS or Mac line breaks to Unix line breaks and vice versa."

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - willend
