{% set name = "dos2unix" %}
{% set version = "7.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://waterlan.home.xs4all.nl/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f811a2b9e4a0c936c61ef7c1732993d1820e5cf011f4d93861885ccb8101ca21

build:
  number: 1

requirements:
  build:
    - {{ compiler ('c') }}
    - {{ stdlib("c") }}
    - make  # [not win]
    - nmake  # [win]
    - gettext-tools
  host:
    - gettext
    - libintl-devel  # [osx]
test:
  commands:
    - dos2unix -h
    - unix2dos -h

about:
  home: https://waterlan.home.xs4all.nl/dos2unix.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: "Convert text files with DOS or Mac line breaks to Unix line breaks and vice versa."

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - willend
