{% set name = "dos2unix" %}
{% set version = "7.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://waterlan.home.xs4all.nl/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28a4b0d9f9179da4e44c567b9c01f818b070a20827115fffd96f760dcfa0f3b2

build:
  number: 1
  script:
    - make prefix=$PREFIX CFLAGS="-I$PREFIX/include $CFLAGS" LDFLAGS="$LDFLAGS" CFLAGS_OS=-I$PREFIX/include status
    - make prefix=$PREFIX CFLAGS="-I$PREFIX/include $CFLAGS" LDFLAGS="$LDFLAGS" CFLAGS_OS=-I$PREFIX/include all
    - make prefix=$PREFIX CFLAGS="-I$PREFIX/include $CFLAGS" LDFLAGS="$LDFLAGS" CFLAGS_OS=-I$PREFIX/include install

requirements:
  build:
    - {{ compiler ('c') }}  # [not win]
    - {{ stdlib("c") }}  # [not win]
    - m2-msys2-runtime   # [win]
    - m2w64-gcc   # [win]
    - m2-sed   # [win]
    - make
    - gettext-tools
  host:
    - gettext
    - libintl-devel  # [osx]
test:
  commands:
    - dos2unix -h
    - unix2dos -h

about:
  home: https://waterlan.home.xs4all.nl/dos2unix.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: "Convert text files with DOS or Mac line breaks to Unix line breaks and vice versa."

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - willend
